language: ruby
rvm:
- 2.2.0
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
before_script:
- gem install bashcov
- gem install coveralls
script:
- bashcov -- ./test.bsh
- ./setup-version.bsh
- tar -X .exclude -C ../ -cvzf /tmp/ci2-$(cat VERSION).tar.gz ci2
# check that we can unarchive our creation
- cd /tmp
- tar -xvzf ci2-$(cat $TRAVIS_BUILD_DIR/VERSION).tar.gz
