language: ruby
rvm:
- 2.2.0
before_script:
- export COVERAGE=yes
- export COV_PROGRAM="bashcov -r coveralls:Coveralls::SimpleCov::Formatter -r codecov:SimpleCov::Formatter::Codecov -r codeclimate-test-reporter:CodeClimate::TestReporter::Formatter --" 
- gem install bashcov
- gem install coveralls
script:
- bashcov -- ./test
